#!/usr/bin/env ruby
require 'yaml'
require 'pp'
require 'stringio'

$LOAD_PATH << File.join(File.dirname(__FILE__), *%w[.. vendor plugins beanstalk_messaging vendor beanstalk-client-1.0.2])
$LOAD_PATH << File.join(File.dirname(__FILE__), *%w[.. vendor plugins beanstalk_messaging lib])

require 'beanstalk_messaging'
require 'beanstalk_manager'

CONFIG_PATH = File.join(File.dirname(__FILE__), *%w[.. config beanstalk.yml])
PID_FOLDER = Beanstalk.custom_pid_directory || File.join(File.dirname(__FILE__), *%w[.. tmp pids])
CONFIG = YAML.load(File.open(CONFIG_PATH))
MANAGER = Beanstalk::DaemonManager.new(PID_FOLDER)

CONFIG.each { |name, settings| MANAGER.register_daemon(name, settings[:host], settings[:port]) }

begin
  case ARGV[0]
  
    when 'start'
      if name = ARGV[1]
        puts "Starting #{name} beanstalk instance..."
        pid = MANAGER.run(name.to_sym)
        puts "Started with pid #{pid}."
      else
        puts "Starting all beanstalk instances..."
        pids = MANAGER.run_all
        puts "Started #{pids.length} beanstalk instances with pids [#{pids.join(',')}]."
      end
  
    when 'stop'
      if name = ARGV[1]
        puts "Stopping #{name} beanstalk instance."
        MANAGER.kill(name.to_sym)
      else
        puts "Stopping all running beanstalk instances."
        MANAGER.kill_all
      end
      puts "Done."
    
    when 'restart'
      if name = ARGV[1]
        puts "Restarting #{name} beanstalk instance..."
        MANAGER.kill(name.to_sym)
        sleep 0.5
        pid = MANAGER.run(name.to_sym)
        puts "Done (pid: [#{pid}])."
      else
        puts "Restarting all beanstalk instances..."
        MANAGER.kill_all
        sleep 0.5
        pids = MANAGER.run_all
        puts "Done (pids: [#{pids.join(',')}])."
      end
    
    when 'status'
      require 'beanstalk_messaging'
      require 'beanstalk/statistics_table_printer'
      
      $stdout = StringIO.new    
      title = "Beanstalk Queue Statistics"
      queue_manager = Beanstalk::QueueManager.load(CONFIG_PATH)
      stats_printer = Beanstalk::StatisticsTablePrinter.new(queue_manager, title)
      rendered_table = stats_printer.render(*MANAGER.configured_queues)
      $stdout = STDOUT
      puts rendered_table
    
    else
      puts "Usage: beanstalk {start|stop|restart|status} [queue_name]"
    
  end
rescue Beanstalk::UnknownDaemon
  puts "Uknown daemon. Please check your configuration file."
  exit 1
end